import type { CaseStudy } from "../types/case-study";

/**
 * Cases em en-GB. Nem tudo neste ficheiro e traduzivel:
 * `slug`, `cover` e `isDemo` identificam o case e tem de ficar iguais nos cinco
 * idiomas, tal como o `href` do credito. Os nomes de cliente sao marcas e
 * normalmente tambem nao se traduzem. Ficam no mesmo objeto na mesma, para o
 * case continuar a ler-se como uma peca so.
 */

/**
 * Todos os cases são reais, com evidência aprovada pelo utilizador em
 * 27/08/2026. Os cases fictícios de demonstração foram removidos em
 * 28/08/2026; para voltar a publicar um case sem evidência ainda aprovada,
 * adicioná-lo com `isDemo: true`.
 */
export const caseStudiesEnGB: CaseStudy[] = [
  {
    slug: "growth-hub",
    client: "Growth Hub",
    sector: "Services and Technology",
    summary: "An entire business with no digital foundation of its own: site, acquisition, content and internal systems all depended on scattered effort.",
    cover: "/cases/growth-hub.webp",
    area: "Digital infrastructure",
    deliverables: [
      "Corporate website",
      "Operational process",
      "Paid traffic and content strategy",
      "AI agent hub system",
      "AI token accounting system",
    ],
    context: "A growing company with no corporate website, no documented sales process and no internal systems to support its AI agent operation.",
    challenge: "Each workstream (site, acquisition, content, operations) moved ahead on its own, with no shared infrastructure and no systems keeping pace with the growth of the team.",
    intervention: "We built the corporate website, the operational process and the paid traffic and content strategy, including the first formats for the experts on the team. In parallel, we designed and implemented two internal systems: an AI agent hub and a token accounting system.",
    structure: "Site, operational process, acquisition strategy and internal AI systems working as a single foundation, without depending on knowledge scattered across the team.",
    results: [
      "A complete digital infrastructure in operation, from the site to the internal systems.",
      "Sales and content process documented and repeatable.",
      "Internal AI systems supporting the daily work of the team.",
    ],
    gallery: [],
  },
  {
    slug: "previa",
    client: "Previa",
    sector: "Financial",
    summary: "A factoring firm whose collections depended on people, and a base of transactions with no commercial reading.",
    cover: "/cases/previa.webp",
    area: "Automation and data intelligence",
    deliverables: ["Collections automation", "Commercial qualification model", "Official channel integration"],
    context: "Previa is a factoring firm that buys receivables from assignors and collects from the drawees responsible for payment. Tracking due dates and chasing payment depended on manual work by the team, and the base of transactions between assignors and drawees was not used beyond collections.",
    challenge: "Collections lost time and consistency by depending on people, and the same base that supported collections hid drawees with the potential to become direct clients, with nobody identifying them.",
    intervention: "Two workstreams structured in parallel. On collections, a system now reads Previa's client base, identifies due dates two days in advance and triggers automatic chasing by email and through official WhatsApp. On commercial intelligence, the base of transactions between assignors and drawees was analysed with a filter defined by Previa, to identify drawees with the potential to become assignors, that is, direct clients.",
    structure: "An automated collections engine connected to the client base and to the official email and WhatsApp channels, with a notice two days before the due date. A data reading process that hands the sales team a qualified list of opportunities generated by the business itself, without depending on manual analysis.",
    results: [
      "Collections no longer depend on manual follow-up by the team.",
      "The sales team now receives qualified opportunities generated by the transaction base itself.",
      "Higher turnover and profit from two complementary workstreams.",
    ],
    gallery: [],
  },
  {
    slug: "falow",
    client: "Falow",
    sector: "Software and SaaS",
    summary: "Instagram automation stuck with the cost and the limits of ManyChat, with no room to become a product of its own.",
    cover: "/cases/falow.webp",
    area: "Automation and SaaS product",
    deliverables: ["Landing page", "DM and comment automation", "Multi-client SaaS product"],
    context: "Matheus Fonseca automated Instagram DMs and comments through ManyChat, with a recurring monthly cost and automations limited to what the generic tool allowed.",
    challenge: "ManyChat created a fixed cost and held back faster, more specific automations for the business, with no route to turning that capability into a product of its own.",
    intervention: "We built Falow, an in-house SaaS for automating Instagram DMs and comments through keyword rules and sequences, faster to operate than ManyChat. The landing page and the system were designed to sell outside the original audience too, as an independent product.",
    structure: "An automation engine driven by keyword rules and sequences, a landing page of its own and a system ready to serve clients outside the original audience.",
    results: [
      "Replacing ManyChat cut cost and sped up the automation operation.",
      "Falow now exists as a product of its own, sellable outside the original audience.",
      "A new turnover workstream, with profitability separate from the original business.",
    ],
    gallery: [],
    credit: { label: "@matheusfonseca.ia", href: "https://www.instagram.com/matheusfonseca.ia/" },
  },
  {
    slug: "rede-de-moteis",
    client: "Cozumel, Manhattan and Atenas",
    sector: "Software and SaaS",
    summary: "A chain of three motels with customer contact scattered across WhatsApp and Instagram, with no single system to manage it all.",
    cover: "/cases/rede-de-moteis.webp",
    area: "Customer service system",
    deliverables: [
      "Service CRM",
      "Official and unofficial WhatsApp integration",
      "Instagram integration",
      "Multi-login by role",
      "Finance and campaign control",
    ],
    context: "A chain of three motels, the Cozumel, the Manhattan and the Atenas, with customer contact scattered across WhatsApp and Instagram, with no single system linking conversations, campaigns and finance.",
    challenge: "Each motel ran its customer contact its own way, with more than five WhatsApp numbers active at the same time and no central control over who saw what, from the agent to the manager.",
    intervention: "We built a service CRM of their own, with the official and unofficial WhatsApp API, Instagram integrated into the same panel, campaign control and a finance module. Multi-login separates access by role: administrator, unit manager and agents.",
    structure: "A single system supporting simultaneous contact across more than five WhatsApp numbers and Instagram, with access segmented by role and ready to take on new motels in the chain.",
    results: [
      "Customer contact for the three motels now runs inside the same system.",
      "More than five WhatsApp numbers managed at the same time without losing control.",
      "A structure ready to expand to new motels in the chain.",
    ],
    gallery: [],
  },
  {
    slug: "brasil-dtf",
    client: "Brasil DTF",
    sector: "Printing Industry",
    summary: "A DTF printer company with no site to support Google campaigns and no digital tool for the garment print market it already served.",
    cover: "/cases/brasil-dtf.webp",
    area: "Corporate website and SaaS product",
    deliverables: [
      "Corporate landing page optimised for Google Ads",
      "Technical SEO and mobile performance",
      "Stamp AI (Halftone Studio), a SaaS for print post-production",
      "Multi-company system with login and subscription plan",
    ],
    context: "Brasil DTF sells DTF and UV DTF printers to retailers and garment print manufacturers, but had no site to support Google campaigns and no digital tool beyond selling the machines themselves.",
    challenge: "Without a fast, well structured site, the investment in Google Ads lost efficiency, and the garment print market Brasil DTF already served (retailers who need to remove backgrounds and apply halftone to artwork before printing) had no affordable tool for the job.",
    intervention: "We built a corporate site to a professional landing page standard, optimised for SEO and for Google campaigns, validated on speed and mobile performance. In parallel, we developed Stamp AI (Halftone Studio), an in-house SaaS for the garment print market, with background removal, image generation and upscaling and different halftone techniques, ready for the workflow of anyone printing garment designs.",
    structure: "A fast corporate site optimised for paid traffic and organic search, and a separate SaaS platform with a multi-company system, its own login per shop, a token system and the image post-production tools the garment print market needs.",
    results: [
      "Site validated on speed and mobile performance, ready to support Google campaigns.",
      "Stamp AI (Halftone Studio) launched as an in-house SaaS, today with more than 20 active retailers.",
      "A new turnover workstream for Brasil DTF, outside printer sales.",
    ],
    gallery: [],
  },
  {
    slug: "sac-automoveis",
    client: "SAC Automóveis",
    sector: "Automotive Retail",
    summary: "Instagram with no commercial pull, and no workstream to buy vehicles on competitive terms, when profitability in automotive retail begins before the sale.",
    cover: "/cases/sac-automoveis.webp",
    area: "Commercial strategy, marketing and profitability",
    deliverables: [
      "Instagram authority",
      "Audience growth",
      "Sales funnels",
      "Campaigns for fairs and internal events",
      "Vehicle acquisition campaigns for better margin",
    ],
    context: "SAC Automóveis needed to strengthen its digital presence and turn Instagram into an active commercial workstream. But the challenge did not end at the sale: in automotive retail, profitability also begins with buying the vehicle and with the quality of the stock entering the business.",
    challenge: "It was necessary to act at both ends of the business: generate more sales opportunities and create campaigns capable of attracting vehicles to buy on more competitive terms. The strategy needed to grow audience and authority, support the internal fairs and improve the dealership's ability to buy, price and sell with more margin.",
    intervention: "Safe structured a marketing and sales strategy to expand SAC's presence on Instagram, grow the follower base and consolidate the brand's authority in the automotive market. In parallel, it developed funnels and campaigns for internal events, fairs and vehicle acquisition. Communication began working both the demand from buyers and the pull of stock opportunities with greater profitability potential.",
    structure: "A marketing operation connected to the full business cycle: authority → audience → buying campaigns → stock → selling campaigns → fairs → margin. Instagram stopped being just a shop window: it went on to support vehicle intake, demand generation and profitability per sale.",
    results: [
      "Growth in the follower base and reinforced authority for SAC Automóveis on Instagram.",
      "Structured campaigns generating opportunities to buy and sell vehicles, including fairs and internal events.",
      "Marketing connected to the margin of the business: more capacity to buy better, build stock with more potential and sell with more profitability.",
    ],
    gallery: [],
  },
  {
    slug: "new-car-automoveis",
    client: "New Car Automóveis",
    sector: "Automotive Retail",
    summary: "An inland car dealership relying on periodic car fairs, with no way to qualify the volume of leads from paid traffic or reactivate its base of old contacts.",
    cover: "/cases/new-car-automoveis.webp",
    area: "Paid traffic, service automation and car fair management",
    deliverables: [
      "Paid traffic campaign management for car fairs",
      "Creative production",
      "Messaging campaigns to the base of old leads",
      "AI agent for lead pre-qualification",
      "AI agent for sales conversion",
    ],
    context: "New Car Automóveis is an inland car dealership that relied on periodic car fairs to sell, but generated paid traffic without being able to filter which leads were worth the sales team's time, or reactivate the base of old leads sitting idle in the CRM.",
    challenge: "The volume of leads generated by the campaigns and by the messages sent to the old base was too large for manual handling. Without pre-qualification, the sales team lost time on leads with no real intention to buy, and the old contact base was forgotten between one car fair and the next.",
    intervention: "Safe took over the management of paid traffic campaigns focused on the car fairs, with in-house creative production, and structured a messaging strategy to reactivate the dealership's base of old leads. To handle the volume, it developed two AI agents: one for pre-service, which qualified every paid traffic lead before passing it on to the sales team, discarding the ones without qualification, and another dedicated to approaching the leads from the messaging campaigns and taking them through to the sale.",
    structure: "Two workstreams connected to the same goal: paid traffic and creatives feeding the car fairs, with one AI agent filtering what reached the sales team, and messages to the old base worked by a second AI agent through to conversion. The sales team only received leads that had already been qualified.",
    results: [
      "More than 50 cars sold in a single car fair.",
      "All paid traffic leads pre-qualified by AI before reaching the sales team, with the ones without qualification discarded.",
      "Reactivation of the old lead base with an AI agent dedicated to converting the messaging campaigns into sales.",
    ],
    gallery: [],
  },
];
