import type { CaseStudy } from "../types/case-study";

/**
 * Cases em en-US. Nem tudo neste ficheiro e traduzivel:
 * `slug`, `cover` e `isDemo` identificam o case e tem de ficar iguais nos cinco
 * idiomas, tal como o `href` do credito. Os nomes de cliente sao marcas e
 * normalmente tambem nao se traduzem. Ficam no mesmo objeto na mesma, para o
 * case continuar a ler-se como uma peca so.
 */

/**
 * Todos os cases são reais, com evidência aprovada pelo utilizador em
 * 27/08/2026. Os cases fictícios de demonstração foram removidos em
 * 28/08/2026; para voltar a publicar um case sem evidência ainda aprovada,
 * adicioná-lo com `isDemo: true`.
 */
export const caseStudiesEnUS: CaseStudy[] = [
  {
    slug: "growth-hub",
    client: "Growth Hub",
    sector: "Services and Technology",
    summary: "An entire operation with no digital foundation of its own: site, acquisition, content and internal systems all ran on scattered effort.",
    cover: "/cases/growth-hub.webp",
    area: "Digital infrastructure",
    deliverables: [
      "Corporate website",
      "Operating process",
      "Paid traffic and content strategy",
      "AI agent hub system",
      "AI token accounting system",
    ],
    context: "A growing company with no corporate website, no documented sales process and no internal systems to support an operation built on AI agents.",
    challenge: "Each workstream (site, acquisition, content, operations) moved on its own, with no shared infrastructure and no systems that kept up with the growth of the team.",
    intervention: "Build of the corporate website, the operating process and the paid traffic and content strategy, including the first formats for the experts on the team. In parallel, design and rollout of two internal systems: an AI agent hub and a token accounting system.",
    structure: "Site, operating process, acquisition strategy and internal AI systems working as a single foundation, without depending on knowledge scattered across the team.",
    results: [
      "Full digital infrastructure in operation, from the site to the internal systems.",
      "Sales and content process documented and repeatable.",
      "Internal AI systems holding up the team's daily operation.",
    ],
    gallery: [],
  },
  {
    slug: "previa",
    client: "Previa",
    sector: "Financial",
    summary: "A receivables firm with collections that depended on people and an operations database with no commercial reading.",
    cover: "/cases/previa.webp",
    area: "Automation and data intelligence",
    deliverables: ["Collections automation", "Commercial qualification model", "Official channel integration"],
    context: "Previa is a receivables firm that buys receivables from assignors and collects from the payers responsible for settling them. Tracking due dates and running collections depended on manual work by the team, and the operations database linking assignors and payers was not used beyond collections.",
    challenge: "Collections lost time and consistency by depending on people, and the same database that supported collections was hiding payers with the potential to become direct clients, with nobody identifying them.",
    intervention: "Two workstreams structured in parallel. In collections, a system started reading Previa's client base, flagging due dates two days ahead and triggering automatic collection by email and through official WhatsApp. In commercial intelligence, the operations database linking assignors and payers was analyzed with a filter defined by Previa, to identify payers with the potential to become assignors, that is, direct clients.",
    structure: "An automated collections engine connected to the client base and to the official email and WhatsApp channels, with a notice two days before the due date. A data reading process that hands the sales team a qualified list of opportunities generated by the operation itself, without depending on manual analysis.",
    results: [
      "Collections no longer depend on manual follow-up by the team.",
      "Sales now receives qualified opportunities generated by the operations database itself.",
      "Higher revenue and profit from two complementary workstreams.",
    ],
    gallery: [],
  },
  {
    slug: "falow",
    client: "Falow",
    sector: "Software and SaaS",
    summary: "Instagram automation locked into the cost and the limits of ManyChat, with no room to become a product of its own.",
    cover: "/cases/falow.webp",
    area: "Automation and SaaS product",
    deliverables: ["Landing page", "DM and comment automation", "Multi-client SaaS product"],
    context: "Matheus Fonseca automated Instagram DMs and comments through ManyChat, with a recurring monthly cost and automations limited to what the generic tool allowed.",
    challenge: "ManyChat created a fixed cost and blocked faster, more specific automations for the operation, with no path to turn that capability into a product of its own.",
    intervention: "Build of Falow, an in-house SaaS for automating Instagram DMs and comments through keyword rules and sequences, faster to operate than ManyChat. The landing page and the system were designed to sell outside the original audience as well, as a standalone product.",
    structure: "An automation engine driven by keyword rules and sequences, its own landing page and a system ready to serve clients outside the original audience.",
    results: [
      "Replacing ManyChat cut cost and sped up the automation operation.",
      "Falow now exists as a product of its own, sellable outside the original audience.",
      "A new revenue stream, with profitability separate from the original operation.",
    ],
    gallery: [],
    credit: { label: "@matheusfonseca.ia", href: "https://www.instagram.com/matheusfonseca.ia/" },
  },
  {
    slug: "rede-de-moteis",
    client: "Cozumel, Manhattan and Atenas",
    sector: "Software and SaaS",
    summary: "A three motel chain with customer service scattered between WhatsApp and Instagram, with no single system to run it all.",
    cover: "/cases/rede-de-moteis.webp",
    area: "Customer service system",
    deliverables: [
      "Customer service CRM",
      "Official and unofficial WhatsApp integration",
      "Instagram integration",
      "Multi-login by role",
      "Finance and campaign control",
    ],
    context: "A chain with three motels, Cozumel, Manhattan and Atenas, with customer service scattered between WhatsApp and Instagram, with no single system tying conversations, campaigns and finance together.",
    challenge: "Each motel ran customer service its own way, with more than five WhatsApp numbers active at the same time and no central control over who saw what, from the agent to the manager.",
    intervention: "Build of an in-house customer service CRM, with official and unofficial WhatsApp API, Instagram inside the same panel, campaign control and a finance module. Multi-login separates access by role: administrator, store manager and agents.",
    structure: "A single system supporting simultaneous service across more than five WhatsApp numbers and Instagram, with access segmented by role and ready to take on new motels in the chain.",
    results: [
      "Customer service for the three motels now runs inside the same system.",
      "More than five WhatsApp numbers managed at the same time without losing control.",
      "A structure ready to expand to new motels in the chain.",
    ],
    gallery: [],
  },
  {
    slug: "brasil-dtf",
    client: "Brasil DTF",
    sector: "Printing Industry",
    summary: "A DTF printer company with no site to support Google campaigns and no digital tool for the print market it already served.",
    cover: "/cases/brasil-dtf.webp",
    area: "Corporate site and SaaS product",
    deliverables: [
      "Corporate landing page optimized for Google Ads",
      "Technical SEO and mobile performance",
      "Stamp AI (Halftone Studio), a SaaS for print post-production",
      "Multi-company system with login and subscription plan",
    ],
    context: "Brasil DTF sells DTF and UV DTF printers to store owners and print manufacturers, but had no site to support Google campaigns and no digital tool beyond selling the machines themselves.",
    challenge: "Without a fast, well structured site, the investment in Google Ads lost efficiency, and the print market Brasil DTF already served (store owners who need to remove backgrounds and apply halftone to artwork before printing) had no affordable tool for it.",
    intervention: "Build of a corporate site to a professional landing page standard, optimized for SEO and for Google campaigns, validated on speed and mobile performance. In parallel, development of Stamp AI (Halftone Studio), an in-house SaaS for the print market, with background removal, image generation and upscaling and different halftone techniques, ready for the workflow of anyone printing artwork.",
    structure: "A fast corporate site optimized for paid traffic and organic search, and a separate SaaS platform with a multi-company system, its own login per store, a token system and the image post-production tools the print market needs.",
    results: [
      "Site validated on speed and mobile performance, ready to support Google campaigns.",
      "Stamp AI (Halftone Studio) launched as an in-house SaaS, today with more than 20 active store owners.",
      "A new revenue stream for Brasil DTF, beyond the sale of printers.",
    ],
    gallery: [],
  },
  {
    slug: "sac-automoveis",
    client: "SAC Automóveis",
    sector: "Automotive Retail",
    summary: "Instagram with no commercial pull and no workstream for buying vehicles on competitive terms, when profitability in auto retail starts before the sale.",
    cover: "/cases/sac-automoveis.webp",
    area: "Commercial strategy, marketing and profitability",
    deliverables: [
      "Instagram authority",
      "Audience growth",
      "Sales funnels",
      "Campaigns for trade shows and in-house events",
      "Vehicle acquisition campaigns for better margin",
    ],
    context: "SAC Automóveis needed to strengthen its digital presence and turn Instagram into an active sales channel. But the challenge did not end at the sale: in auto retail, profitability also starts with buying the vehicle and with the quality of the inventory that enters the operation.",
    challenge: "The work had to cover both ends of the business: generating more sales opportunities and creating campaigns able to attract vehicles for purchase on more competitive terms. The strategy needed to grow audience and authority, support the in-house trade shows, and improve the dealership's ability to buy, price and sell with more margin.",
    intervention: "Safe built a marketing and sales strategy to expand SAC's presence on Instagram, grow its follower base and establish the brand's authority in the auto market. In parallel, it developed funnels and campaigns for in-house events, trade shows and vehicle acquisition. Communication began working both sides: demand from buyers and the pull of inventory opportunities with stronger profit potential.",
    structure: "A marketing operation tied to the full cycle of the business: authority → audience → buying campaigns → inventory → selling campaigns → trade shows → margin. Instagram stopped being just a showcase: it began supporting vehicle intake, demand generation and profitability per sale.",
    results: [
      "Growth in the follower base and stronger authority for SAC Automóveis on Instagram.",
      "Structured campaigns generating opportunities to buy and sell vehicles, including trade shows and in-house events.",
      "Marketing tied to the operation's margin: more capacity to buy better, build inventory with stronger potential and sell with more profitability.",
    ],
    gallery: [],
  },
  {
    slug: "new-car-automoveis",
    client: "New Car Automóveis",
    sector: "Automotive Retail",
    summary: "An inland dealership relying on periodic sales events, with no way to qualify the volume of leads from paid traffic or reactivate its base of old contacts.",
    cover: "/cases/new-car-automoveis.webp",
    area: "Paid traffic, service automation and sales event management",
    deliverables: [
      "Paid traffic campaign management for sales events",
      "Creative production",
      "Message blasts to the base of old leads",
      "AI lead pre-qualification agent",
      "AI sales conversion agent",
    ],
    context: "New Car Automóveis is an inland dealership that relied on periodic sales events to sell, but ran paid traffic without being able to filter which leads were worth the sales team's time or reactivate the old leads sitting idle in the CRM.",
    challenge: "The volume of leads generated by the campaigns and by the blasts to the old lead base was too large for manual handling. Without pre-qualification, sales reps lost time on leads with no real intent to buy, and the old contact base sat forgotten between one sales event and the next.",
    intervention: "Safe took over management of paid traffic campaigns focused on the sales events, with in-house creative production, and built a message blast strategy to reactivate the dealership's old lead base. To handle the volume, it developed two AI agents: one for pre-qualification, screening every paid traffic lead before passing it on to sales reps and discarding the unqualified ones, and another dedicated to reaching out to the blast leads and guiding them through to the sale.",
    structure: "Two workstreams tied to the same goal: paid traffic and creatives feeding the sales events, with an AI agent filtering what reached the sales reps, and blasts to the old lead base worked by a second AI agent through to conversion. Sales reps only received leads that were already qualified.",
    results: [
      "More than 50 cars sold at a single sales event.",
      "Every paid traffic lead pre-qualified by AI before reaching the sales team, with unqualified leads discarded.",
      "Reactivation of the old lead base with an AI agent dedicated to converting the blast leads into sales.",
    ],
    gallery: [],
  },
];
